export default {
    SET_TECHNOLOGY: 'SET_TECHNOLOGY',
    INCREASE_AMOUNT: 'INCREASE_AMOUNT',
    DECREASE_AMOUNT: 'DECREASE_AMOUNT',
    REMOVE_TODO_ITEM: 'REMOVE_TODO_ITEM',
    UPDATE_TODO_ITEM: 'UPDATE_TODO_ITEM',
    FETCHING_DATA : 'FETCHING_DATA',
    FETCHING_DATA_SUCCESS : 'FETCHING_DATA_SUCCESS',
    FETCHING_DATA_FAILURE : 'FETCHING_DATA_FAILURE'
}