export default {
    SET_TECHNOLOGY : 'SET_TECHNOLOGY',
    INCREASE_AMOUNT : 'INCREASE_AMOUNT',
    DECREASE_AMOUNT : 'DECREASE_AMOUNT',
    REMOVE_TODO_ITEM : 'REMOVE_TODO_ITEM',
    UPDATE_TODO_ITEM : 'UPDATE_TODO_ITEM'
}